<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXaUfrnV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXaUfrnV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXaUfrnV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXaUfrnV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXaUfrnV\App_KernelDevDebugContainer([
    'container.build_hash' => 'XaUfrnV',
    'container.build_id' => 'f1fafec7',
    'container.build_time' => 1639955912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXaUfrnV');
