<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTIbtjft\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTIbtjft/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTIbtjft.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTIbtjft\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTIbtjft\App_KernelDevDebugContainer([
    'container.build_hash' => 'TIbtjft',
    'container.build_id' => '0ebf03dd',
    'container.build_time' => 1639950188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTIbtjft');
